const path = '../../assets/images'
export const AppAssets = {
    eyeOpen: require(`${path}/png/EyeOpen.png`),
    eyeClose: require(`${path}/png/EyeClose.png`),
    inActive: require(`${path}/png/checkfalse.png`),
    Active: require(`${path}/png/Active.png`),
    closeLarge: require(`${path}/png/closelarge.png`),
    search: require(`${path}/png/Search.png`),
    menu: require(`${path}/png/menu.png`),
    arrowUp: require(`${path}/png/arrowUp.png`),
    arrowDown: require(`${path}/png/arrowDown.png`),
    filter: require(`${path}/png/filter.png`),
    logout: require(`${path}/png/logout.png`),
    Homepage: require(`${path}/png/Homepage.png`),
    catbg: require(`${path}/png/cat.png`),
    back: require(`${path}/png/back.png`),
    next: require(`${path}/png/next.png`),
    full: require(`${path}/png/full.png`),
    stretch: require(`${path}/png/stretch.png`),
    orignal: require(`${path}/png/orignal.png`),
    low: require(`${path}/png/low.png`),
    mute: require(`${path}/png/mute.png`),
    unmute: require(`${path}/png/unmute.png`),
    pause: require(`${path}/png/pause.png`),
    play: require(`${path}/png/play.png`),
    seekback: require(`${path}/png/seekbac.png`),
    seekfor: require(`${path}/png/seekfor.png`),
    prev: require(`${path}/png/prev.png`),
    pip: require(`${path}/png/PIP.png`),
    whatsapp: require(`${path}/png/whatsapp.png`)
}